# Generated by Django 2.0.6 on 2019-08-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='state',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
